name: Manual React Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Or your preferred version

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Upload React build artifact
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: build/
