name: Central Workflow

on:
  workflow_dispatch:

jobs:
  run-build:
    uses: ./.github/workflows/build.yaml

  run-maven:
    needs: run-build
    uses: ./.github/workflows/maven.yml

  run-sonarqube:
    needs: run-maven
    uses: ./.github/workflows/SonarQube.yml

